/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:dotMark': typeof import('~icons/carbon/dot-mark')['default']
    'Carbon:language': typeof import('~icons/carbon/language')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
